### ISSUE TITLE
Make suites easier to use

### ISSUE THREAD

**Issue by cgay** [dylan-lang/testworks#111]
It's too easy to forget to add tests/suites to the top-level suite.  For example, as I'm working on simplifying specs I'm adapting dylan-test-suite to it and keep forgetting to transitively add them to dylan-test-suite.

If instead of this
```
define suite dylan-test-suite ()
  suite dylan-interface-test-suite;
  suite dylan-control-test-suite;
  suite dylan-regressions-test-suite;
  suite types-test-suite;
end;
```
we could write this
```
define suite dylan-test-suite ()
  make-root-test-suite();
end;
```
this wouldn't be a problem.

**Comment by cgay** [comment]
This will have problems when multiple libraries' test suites are combined because `make-root-test-suite()` will return the exact same suite for all libraries (because there's a global test registry).

Maybe the best way to deal with it is to make root suites special (e.g., a subclass of `<suite>`) and only ever allow one root suite.   Or just run tests as executables, not combined libraries.

**Comment by housel** [comment]
I find that with my current workflow this isn't a problem. In particular, I load test libraries using `testworks-run --load` (resulting in an automatic call to `make-root-test-suite()`, and use the `full` report format, which makes the suite hierarchy obvious.

**Comment by cgay** [comment]
Interesting. I just tried that with `generic-test-suite` and ran into a different problem: `system` and `io` have streams-related suites with the same names, which causes `find-root-components` to err.  I think instead I should make testworks signal an error when a duplicate name is registered.

**Comment by cgay** [comment]
https://github.com/dylan-lang/testworks/pull/113

**Comment by cgay** [comment]
ok, we'll either call `run-test-application()` with no args, or use `testworks-run`.
