### ISSUE TITLE
Set up continuous integration (CI) for testworks

### ISSUE THREAD

**Issue by cgay** [dylan-lang/testworks#147]
https://github.com/dylan-lang/testworks/blob/master/.github/workflows/linux-od-test2.yml is where I left off, and I posted this question to github forums: https://github.community/t/workflow-command-hanging-with-no-output/126696

I wonder if using the 2020.1 "batteries included" release would work any better. Might as well try it...

**Comment by fraya** [comment]
Unless @cgay thinks otherwise, I think that the purpose of linux-od-test2.yml is cover by current GH Actions.

**Comment by cgay** [comment]
Yes, this seems obsolete. Closing.
