### ISSUE TITLE
Loading library writes to *stdout* in conflict with  '--progress none --report surefire'

### ISSUE THREAD

**Issue by fraya** [dylan-lang/testworks#176]
When testworks loads a library writes to `*stdout*` making unusable the 'report' output.

See line
https://github.com/dylan-lang/testworks/blob/5a779d9511685293c7564de609f076da44756644/command-line.dylan#L124

**Comment by cgay** [comment]
We should revert the change i made to remove the `--report-file` option in one of my occasional fits of minimalism.
