### ISSUE TITLE
testworks-specs, test-unit, tags

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/testworks#42]
We need to do something about testworks-specs using test-units.

My suggestion would be that we extend the suite-definer to allow inline tests, then where we use tests with test-units in them can become suites with inline tests.

Without addressing this, we can't ignore things in the specs-based tests at a low level (we have to ignore whole huge swathes of test units).

**Comment by cgay** [comment]
This will be fixed as part of my upcoming simplification of specs, which will just do one, specific thing: check that the implementation matches the spec. Other kinds of tests should be written with normal `define suite` and `define test` macros.

**Comment by cgay** [comment]
Testworks (specs) no longer uses test units.
