### ISSUE TITLE
No way for a testworks user to get the runner-output-stream

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/testworks#66]
In some tests, I'd like to get the runner's output stream. While ``runner-output-stream`` is exported from ``testworks``, the ``*runner*`` variable is not, nor is any utility function for getting that value to pass through to ``runner-output-stream``.

**Comment by waywardmonkeys** [comment]
Ping @cgay!

**Comment by cgay** [comment]
Sure, exporting ``*runner*`` seems reasonable.

**Comment by waywardmonkeys** [comment]
Fixed in c0f15f8d0fa635e1c0eedcf53c2e0b6cf5fed2ad.
